eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka/
server:
  port: 8892
spring:
  application:
    name: service-feign
#¿ªÆôfeignÈÛ¶Ï×¢½â
feign:
  hystrix:
    enabled: true
